version: '3.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=consigmais
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - .:/usr/src/mysql